[package]
name = "ruffini"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Algebraic structures over arbitrary-precision integers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["demos"]

[dependencies]
num-bigint = "0.4.6"
itertools = "0.15.0"
num-traits = "0.2.19"
