//! Gröbner bases, by Buchberger's algorithm with his two criteria.
//!
//! A Gröbner basis of an ideal, for a given monomial order, is a generating set whose
//! leading monomials generate the ideal's whole leading-term ideal. That is what makes
//! division by it well defined: the remainder no longer depends on the order the
//! divisors are listed in, so `p` lies in the ideal exactly when it reduces to zero.

use crate::multivariate::{
    divide, divides, lcm, Monomial, MonomialOrder, MultivariatePolynomial,
    MultivariatePolynomialRing,
};
use crate::structures::{CommutativeMonoid, Domain, Field, RingOps};
use std::rc::Rc;

/// The reduced Gröbner basis of the ideal generated by `generators`, under `order`.
///
/// Reduced means monic, with no leading monomial dividing another and no term divisible
/// by another element's leading monomial. That basis is unique for a given ideal and
/// order, so two generating sets of the same ideal give the same answer here.
///
/// The empty ideal gives an empty basis. Worst-case cost is doubly exponential in the
/// number of variables, which is intrinsic to the problem rather than to this code.
pub fn grobner_basis<R>(
    ring: &Rc<MultivariatePolynomialRing<R>>,
    generators: &[MultivariatePolynomial<R>],
    order: &impl MonomialOrder,
) -> Vec<MultivariatePolynomial<R>>
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    let zero = ring.zero();
    let mut basis: Vec<MultivariatePolynomial<R>> =
        generators.iter().filter(|g| **g != zero).cloned().collect();
    if basis.is_empty() {
        return Vec::new();
    }

    let mut pending: Vec<(usize, usize)> = (0..basis.len())
        .flat_map(|i| (i + 1..basis.len()).map(move |j| (i, j)))
        .collect();

    while let Some(at) = select(&basis, &pending, order) {
        let (i, j) = pending.swap_remove(at);
        if discard(&basis, &pending, i, j, order) {
            continue;
        }

        let s = s_polynomial(ring, &basis[i], &basis[j], order);
        let remainder = s.divide(&basis, order).1;
        if remainder == zero {
            continue;
        }

        // A new generator pairs with everything already there.
        let new = basis.len();
        pending.extend((0..new).map(|k| (k, new)));
        basis.push(remainder);
    }

    reduce(ring, basis, order)
}

/// The pair whose lcm is smallest, by total degree and then by `order`.
///
/// Buchberger's normal strategy: handling small pairs first tends to produce generators
/// that reduce the later ones away, so fewer S-polynomials survive at all.
fn select<R>(
    basis: &[MultivariatePolynomial<R>],
    pending: &[(usize, usize)],
    order: &impl MonomialOrder,
) -> Option<usize>
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    pending
        .iter()
        .enumerate()
        .min_by(|(_, &(a, b)), (_, &(c, d))| {
            let left = lcm(
                lead_monomial(&basis[a], order),
                lead_monomial(&basis[b], order),
            );
            let right = lcm(
                lead_monomial(&basis[c], order),
                lead_monomial(&basis[d], order),
            );
            let (dl, dr) = (left.iter().sum::<u32>(), right.iter().sum::<u32>());
            dl.cmp(&dr).then_with(|| order.cmp(&left, &right))
        })
        .map(|(at, _)| at)
}

/// Whether the pair `(i, j)` can be skipped without computing its S-polynomial.
///
/// Buchberger's first criterion: leading monomials sharing no variable give an
/// S-polynomial that always reduces to zero, so the lcm being their product settles it.
///
/// His second, the chain criterion: if some `k` has a leading monomial dividing the
/// lcm, and the pairs `(i, k)` and `(j, k)` have both already been handled, then this
/// pair reduces to zero as a consequence of those two.
fn discard<R>(
    basis: &[MultivariatePolynomial<R>],
    pending: &[(usize, usize)],
    i: usize,
    j: usize,
    order: &impl MonomialOrder,
) -> bool
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    let (a, b) = (
        lead_monomial(&basis[i], order),
        lead_monomial(&basis[j], order),
    );
    let l = lcm(a, b);

    // Coprime: the lcm is the product exactly when no variable appears in both.
    if a.iter().zip(b).all(|(x, y)| *x == 0 || *y == 0) {
        return true;
    }

    (0..basis.len()).any(|k| {
        k != i
            && k != j
            && divides(lead_monomial(&basis[k], order), &l)
            && !is_pending(pending, i, k)
            && !is_pending(pending, j, k)
    })
}

fn is_pending(pending: &[(usize, usize)], a: usize, b: usize) -> bool {
    let pair = (a.min(b), a.max(b));
    pending.contains(&pair)
}

/// `S(f, g)`: the combination that cancels the two leading terms, which is the only
/// way a leading term can fail to be divisible by some leading term of the basis.
fn s_polynomial<R>(
    ring: &Rc<MultivariatePolynomialRing<R>>,
    f: &MultivariatePolynomial<R>,
    g: &MultivariatePolynomial<R>,
    order: &impl MonomialOrder,
) -> MultivariatePolynomial<R>
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    let field = ring.coefficients();
    let (fm, fc) = f.lead(order).expect("S-polynomial of the zero polynomial");
    let (gm, gc) = g.lead(order).expect("S-polynomial of the zero polynomial");
    let l = lcm(fm, gm);

    let scale = |m: &Monomial, c: &R::E| {
        let inverse = field.invert(c).expect("a leading coefficient is nonzero");
        ring.element(vec![(divide(&l, m), inverse)])
    };
    // Owned operands: the borrowed ones would put a higher-ranked bound on the
    // coefficients into this module's whole public signature, for one product a pair.
    scale(fm, fc) * f.clone() - scale(gm, gc) * g.clone()
}

/// Cuts a Gröbner basis down to the reduced one: monic, no leading monomial dividing
/// another, and no term divisible by another element's leading monomial.
fn reduce<R>(
    ring: &Rc<MultivariatePolynomialRing<R>>,
    basis: Vec<MultivariatePolynomial<R>>,
    order: &impl MonomialOrder,
) -> Vec<MultivariatePolynomial<R>>
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    // Minimal: drop any element whose leading monomial another one already divides.
    // Equal leading monomials keep the earlier element, so exactly one survives.
    let mut minimal: Vec<MultivariatePolynomial<R>> = Vec::new();
    for (i, g) in basis.iter().enumerate() {
        let lm = lead_monomial(g, order);
        let covered = basis.iter().enumerate().any(|(k, h)| {
            let other = lead_monomial(h, order);
            k != i && divides(other, lm) && (other != lm || k < i)
        });
        if !covered {
            minimal.push(g.clone());
        }
    }

    // Each element is then reduced against the others. Its own leading term survives -
    // no other leading monomial divides it - so none of these becomes zero.
    for i in 0..minimal.len() {
        let others: Vec<MultivariatePolynomial<R>> = minimal
            .iter()
            .enumerate()
            .filter(|(k, _)| *k != i)
            .map(|(_, g)| g.clone())
            .collect();
        let reduced = if others.is_empty() {
            minimal[i].clone()
        } else {
            minimal[i].divide(&others, order).1
        };
        minimal[i] = monic(ring, &reduced, order);
    }

    // Sorted by leading monomial, descending, so the answer is canonical.
    minimal.sort_by(|a, b| order.cmp(lead_monomial(b, order), lead_monomial(a, order)));
    minimal
}

/// Scales so the leading coefficient is one.
fn monic<R>(
    ring: &Rc<MultivariatePolynomialRing<R>>,
    p: &MultivariatePolynomial<R>,
    order: &impl MonomialOrder,
) -> MultivariatePolynomial<R>
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    let (_, lc) = p.lead(order).expect("a basis element is nonzero");
    let inverse = ring
        .coefficients()
        .invert(lc)
        .expect("a leading coefficient is nonzero");
    let terms: Vec<(Monomial, R::E)> = p
        .terms()
        .map(|(m, c)| (m.clone(), inverse.clone() * c.clone()))
        .collect();
    ring.element(terms)
}

fn lead_monomial<'a, R>(
    p: &'a MultivariatePolynomial<R>,
    order: &impl MonomialOrder,
) -> &'a Monomial
where
    R: Field + Clone,
    R::E: RingOps + Eq,
{
    p.lead(order).expect("a basis element is nonzero").0
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::integers::Integers;
    use crate::multivariate::{GradedLex, Lex};
    use crate::polynomials::RingExt;
    use crate::structures::Monoid;

    type F7 = Rc<crate::structures::QuotientRing<Integers>>;
    type Ring2 = Rc<MultivariatePolynomialRing<F7>>;

    fn f7x2() -> Ring2 {
        Integers::modulo(7).multi_polynomials(2)
    }

    /// The definition: every S-pair of the basis reduces to zero modulo it.
    ///
    /// Computed over all pairs, with no criterion applied, so this also catches a
    /// `discard` that skipped a pair it should not have.
    fn is_grobner_basis<R>(
        ring: &Rc<MultivariatePolynomialRing<R>>,
        basis: &[MultivariatePolynomial<R>],
        order: &impl MonomialOrder,
    ) -> bool
    where
        R: Field + Clone,
        R::E: RingOps + Eq,
    {
        let zero = ring.zero();
        (0..basis.len()).all(|i| {
            (i + 1..basis.len()).all(|j| {
                let s = s_polynomial(ring, &basis[i], &basis[j], order);
                s.divide(basis, order).1 == zero
            })
        })
    }

    #[test]
    fn matches_the_worked_example_in_cox_little_oshea() {
        // f1 = x^3 - 2xy, f2 = x^2 y - 2y^2 + x, over F_7 rather than Q.
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));
        let f1 = x.pow(3) - 2 * x.clone() * y.clone();
        let f2 = x.pow(2) * y.clone() - 2 * y.pow(2) + x.clone();
        let generators = [f1, f2];

        // Graded lex: {x^2, xy, y^2 - x/2}, and 1/2 is 4 in F_7, so -x/2 is 3x.
        let grlex = grobner_basis(&r, &generators, &GradedLex);
        assert_eq!(
            grlex,
            vec![x.pow(2), x.clone() * y.clone(), y.pow(2) + 3 * x.clone()]
        );

        // Lex eliminates x, which is the property the order is chosen for.
        let lex = grobner_basis(&r, &generators, &Lex);
        assert_eq!(lex, vec![x.clone() - 2 * y.pow(2), y.pow(3)]);

        assert!(is_grobner_basis(&r, &grlex, &GradedLex));
        assert!(is_grobner_basis(&r, &lex, &Lex));
    }

    #[test]
    fn a_line_meeting_a_circle_reduces_to_one_variable() {
        // x^2 + y^2 = 1 and x = y, so 2y^2 = 1 and y^2 = 4; -4 is 3 in F_7.
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));
        let generators = [x.pow(2) + y.pow(2) - 1, x.clone() - y.clone()];

        let basis = grobner_basis(&r, &generators, &Lex);
        assert_eq!(basis, vec![x.clone() - y.clone(), y.pow(2) + 3]);
        assert!(is_grobner_basis(&r, &basis, &Lex));
    }

    #[test]
    fn coprime_leading_monomials_are_already_a_basis() {
        // The case Buchberger's first criterion discards: every S-pair reduces to zero
        // without being computed.
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));
        let basis = grobner_basis(&r, &[x.pow(2), y.pow(3)], &Lex);
        assert_eq!(basis, vec![x.pow(2), y.pow(3)]);
        assert!(is_grobner_basis(&r, &basis, &Lex));
    }

    #[test]
    fn the_reduced_basis_is_canonical() {
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));
        let g1 = x.pow(3) - 2 * x.clone() * y.clone();
        let g2 = x.pow(2) * y.clone() - 2 * y.pow(2) + x.clone();
        let expected = grobner_basis(&r, &[g1.clone(), g2.clone()], &GradedLex);

        // Reordered, scaled, and with a combination thrown in: the same ideal.
        let same_ideal = [
            g2.clone() * 3,
            g1.clone(),
            g1.clone() + g2.clone() * 5,
            r.zero(),
        ];
        assert_eq!(grobner_basis(&r, &same_ideal, &GradedLex), expected);

        // And a basis is its own basis.
        assert_eq!(grobner_basis(&r, &expected, &GradedLex), expected);
    }

    #[test]
    fn membership_is_decided_by_reducing_to_zero() {
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));
        let g1 = x.pow(3) - 2 * x.clone() * y.clone();
        let g2 = x.pow(2) * y.clone() - 2 * y.pow(2) + x.clone();
        let basis = grobner_basis(&r, &[g1.clone(), g2.clone()], &GradedLex);

        // Both generators are in the ideal, as is any combination of them.
        for p in [
            g1.clone(),
            g2.clone(),
            g1.clone() * y.clone() + g2.clone() * 4,
        ] {
            assert_eq!(p.divide(&basis, &Lex).1, r.zero());
        }

        // x is not: the basis has x^2, xy and y^2 + 3x, none of whose leading
        // monomials divide it.
        assert_ne!(x.clone().divide(&basis, &GradedLex).1, r.zero());
    }

    #[test]
    fn handles_the_degenerate_ideals() {
        let r = f7x2();
        let (x, y) = (r.variable(0), r.variable(1));

        assert!(grobner_basis(&r, &[], &Lex).is_empty());
        assert!(grobner_basis(&r, &[r.zero(), r.zero()], &Lex).is_empty());

        // A single generator is its own basis, made monic.
        assert_eq!(grobner_basis(&r, &[x.pow(2) * 3], &Lex), vec![x.pow(2)]);

        // x and x + 1 generate everything, so the basis is {1}.
        assert_eq!(
            grobner_basis(&r, &[x.clone(), x.clone() + 1], &Lex),
            vec![r.identity()]
        );

        // Duplicate generators collapse rather than appearing twice.
        assert_eq!(
            grobner_basis(&r, &[y.pow(2), y.pow(2) * 2], &Lex),
            vec![y.pow(2)]
        );
    }

    #[test]
    fn solves_the_cyclic_4_benchmark() {
        // The cyclic roots system: the elementary symmetric-like rotations of four
        // variables, with the product pinned to one. Small, but the first ideal here
        // whose basis is not obvious by hand.
        let f = Integers::modulo(32003);
        let r = f.multi_polynomials(4);
        let v: Vec<_> = (0..4).map(|i| r.variable(i)).collect();
        let rotations = |len: usize| {
            (0..4).fold(r.zero(), |acc, s| {
                acc + (0..len).fold(r.identity(), |p, t| p * v[(s + t) % 4].clone())
            })
        };
        let product = v.iter().fold(r.identity(), |p, x| p * x.clone());
        let generators = [rotations(1), rotations(2), rotations(3), product - 1];

        let basis = grobner_basis(&r, &generators, &GradedLex);

        // Validated by the S-pair criterion rather than taken on trust; the count is
        // here as a regression guard.
        assert!(is_grobner_basis(&r, &basis, &GradedLex));
        assert_eq!(basis.len(), 7);
        for g in &generators {
            assert_eq!(g.divide(&basis, &GradedLex).1, r.zero());
        }

        // Feeding the generators in a different order gives the same reduced basis.
        let shuffled = [
            generators[3].clone(),
            generators[1].clone(),
            generators[0].clone(),
            generators[2].clone(),
        ];
        assert_eq!(grobner_basis(&r, &shuffled, &GradedLex), basis);
    }

    #[test]
    fn works_in_three_variables() {
        // The twisted cubic: y = x^2, z = x^3.
        let r = Integers::modulo(7).multi_polynomials(3);
        let (x, y, z) = (r.variable(0), r.variable(1), r.variable(2));
        let generators = [y.clone() - x.pow(2), z.clone() - x.pow(3)];

        let basis = grobner_basis(&r, &generators, &GradedLex);
        assert!(is_grobner_basis(&r, &basis, &GradedLex));

        // y^2 - xz vanishes on the curve, so it lies in the ideal, while y - z does not.
        assert_eq!(
            (y.pow(2) - x.clone() * z.clone())
                .divide(&basis, &GradedLex)
                .1,
            r.zero()
        );
        assert_ne!(
            (y.clone() - z.clone()).divide(&basis, &GradedLex).1,
            r.zero()
        );
    }
}
